kind = "DojoContract"
class_hash = "0x127fa44350a66090be65727d5d5efde6e6610fda8a1c68bee1ab13344357afc"
original_class_hash = "0x127fa44350a66090be65727d5d5efde6e6610fda8a1c68bee1ab13344357afc"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
