kind = "DojoContract"
class_hash = "0x46018430f63ddcf386d6a3162089e6e9d0a936707c8ed2880fb35fa83a94413"
original_class_hash = "0x46018430f63ddcf386d6a3162089e6e9d0a936707c8ed2880fb35fa83a94413"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
