kind = "DojoContract"
class_hash = "0x3566c3d6d078007bf503d7229a6457b6df85c89aaa4e320201a0b2f6b3ea600"
original_class_hash = "0x3566c3d6d078007bf503d7229a6457b6df85c89aaa4e320201a0b2f6b3ea600"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
