kind = "DojoContract"
class_hash = "0x23a5c6453c8418a3a04b4bf9d879b4ce5546401a911f8b7cf64e9aa45baecfc"
original_class_hash = "0x23a5c6453c8418a3a04b4bf9d879b4ce5546401a911f8b7cf64e9aa45baecfc"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
