[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x3d8ac96b61481d16f5df2342b66a2107272cf551b6f8195f1ce39be3cca13"
transaction_hash = "0x6b42eb9c1a97928cbf83be7db44e1aadd5921e6e11630db5e94a0135ce3fa6f"
block_number = 3
seed = "threed_2048"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x38d4ad3eb3c1fa648214f2cded353832b6ae8d051110e52fbf4451e4f5c3883"
class_hash = "0x23a5c6453c8418a3a04b4bf9d879b4ce5546401a911f8b7cf64e9aa45baecfc"
original_class_hash = "0x23a5c6453c8418a3a04b4bf9d879b4ce5546401a911f8b7cf64e9aa45baecfc"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = [
    "Position",
    "Moves",
    "DirectionsAvailable",
]
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x7d3dd62c0c7b5f7863f011a44be1d125703b8e988978f5d8a72387f547d5ba6"
original_class_hash = "0x7d3dd62c0c7b5f7863f011a44be1d125703b8e988978f5d8a72387f547d5ba6"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_entity_mergeable.json"
name = "threed_2048::models::entity::mergeable"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "can_merge"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6e7a46b3ca8122bcf0fc1c3949f5f4f62e62abf7e6b6f8107c1d6f35617f080"
original_class_hash = "0x6e7a46b3ca8122bcf0fc1c3949f5f4f62e62abf7e6b6f8107c1d6f35617f080"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_entity_movable.json"
name = "threed_2048::models::entity::movable"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x522647c4287815f666af32252dbee98816654f2ed86de42b16649345a6aa9b"
original_class_hash = "0x522647c4287815f666af32252dbee98816654f2ed86de42b16649345a6aa9b"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_entity_position.json"
name = "threed_2048::models::entity::position"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "z"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b7cd2e974d7ca54902b7c06db67748aa93b030abdd0a943b82391f4f6de4f2"
original_class_hash = "0x6b7cd2e974d7ca54902b7c06db67748aa93b030abdd0a943b82391f4f6de4f2"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_entity_value.json"
name = "threed_2048::models::entity::value"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x44d225e79ccf70dd142920fd7bbbbd8afc88bf5709efc68127883e118b3a7ae"
original_class_hash = "0x44d225e79ccf70dd142920fd7bbbbd8afc88bf5709efc68127883e118b3a7ae"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_game_game.json"
name = "threed_2048::models::game::game"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models.members]]
name = "width"
type = "u32"
key = false

[[models.members]]
name = "height"
type = "u32"
key = false

[[models.members]]
name = "tile_count"
type = "u32"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "state"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x99f9eb313335bc9d3427ec2cc90a9ada229580fda26ada13b5a629801bd847"
original_class_hash = "0x99f9eb313335bc9d3427ec2cc90a9ada229580fda26ada13b5a629801bd847"
abi = "manifests/dev/abis/deployments/models/threed_2048_models_player_player.json"
name = "threed_2048::models::player::player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_game_id"
type = "u32"
key = false

[[models.members]]
name = "games_won"
type = "u32"
key = false

[[models.members]]
name = "games_lost"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1ab67114548b64aa4fde2d8d5650195b49d430d707e99f5a1bfc2e1b7957879"
original_class_hash = "0x1ab67114548b64aa4fde2d8d5650195b49d430d707e99f5a1bfc2e1b7957879"
abi = "manifests/dev/abis/deployments/models/threed_2048_systems_actions_actions_moved.json"
name = "threed_2048::systems::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false
