kind = "DojoModel"
class_hash = "0x2cb5c2e63432bd1e828367a19c74ce51a4c5ab740f19e1241098615f30e2ff8"
original_class_hash = "0x2cb5c2e63432bd1e828367a19c74ce51a4c5ab740f19e1241098615f30e2ff8"
abi = "manifests/dev/abis/base/models/threed_2048_models_game_game.json"
name = "threed_2048::models::game::game"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "game_mode"
type = "GameMode"
key = false

[[members]]
name = "box_size"
type = "u32"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "state"
type = "u8"
key = false
