kind = "DojoModel"
class_hash = "0x64f40affb2d321f16b1a4b7b272bca9830547dbff19d13f9c7349b2db62a87e"
original_class_hash = "0x64f40affb2d321f16b1a4b7b272bca9830547dbff19d13f9c7349b2db62a87e"
abi = "manifests/dev/abis/base/models/threed_2048_models_entity_tile.json"
name = "threed_2048::models::entity::tile"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "z"
type = "u32"
key = false

[[members]]
name = "value"
type = "u32"
key = false
