kind = "DojoModel"
class_hash = "0x6e7a46b3ca8122bcf0fc1c3949f5f4f62e62abf7e6b6f8107c1d6f35617f080"
original_class_hash = "0x6e7a46b3ca8122bcf0fc1c3949f5f4f62e62abf7e6b6f8107c1d6f35617f080"
abi = "manifests/dev/abis/base/models/threed_2048_models_entity_movable.json"
name = "threed_2048::models::entity::movable"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = true

[[members]]
name = "can_move"
type = "bool"
key = false
