kind = "DojoModel"
class_hash = "0x6b7cd2e974d7ca54902b7c06db67748aa93b030abdd0a943b82391f4f6de4f2"
original_class_hash = "0x6b7cd2e974d7ca54902b7c06db67748aa93b030abdd0a943b82391f4f6de4f2"
abi = "manifests/dev/abis/base/models/threed_2048_models_entity_value.json"
name = "threed_2048::models::entity::value"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = true

[[members]]
name = "value"
type = "u32"
key = false
