kind = "DojoModel"
class_hash = "0x7d3dd62c0c7b5f7863f011a44be1d125703b8e988978f5d8a72387f547d5ba6"
original_class_hash = "0x7d3dd62c0c7b5f7863f011a44be1d125703b8e988978f5d8a72387f547d5ba6"
abi = "manifests/dev/abis/base/models/threed_2048_models_entity_mergeable.json"
name = "threed_2048::models::entity::mergeable"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = true

[[members]]
name = "can_merge"
type = "bool"
key = false
