kind = "DojoModel"
class_hash = "0x99f9eb313335bc9d3427ec2cc90a9ada229580fda26ada13b5a629801bd847"
original_class_hash = "0x99f9eb313335bc9d3427ec2cc90a9ada229580fda26ada13b5a629801bd847"
abi = "manifests/dev/abis/base/models/threed_2048_models_player_player.json"
name = "threed_2048::models::player::player"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "last_game_id"
type = "u32"
key = false

[[members]]
name = "games_won"
type = "u32"
key = false

[[members]]
name = "games_lost"
type = "u32"
key = false
