kind = "DojoModel"
class_hash = "0x49b4dc8b6b40b4f8a4d441677e79a35817d5d490f25f5e771f6c6785589ab29"
original_class_hash = "0x49b4dc8b6b40b4f8a4d441677e79a35817d5d490f25f5e771f6c6785589ab29"
abi = "manifests/dev/abis/base/models/threed_2048_models_entity_tile.json"
name = "threed_2048::models::entity::tile"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "z"
type = "u32"
key = false

[[members]]
name = "is_alive"
type = "bool"
key = false

[[members]]
name = "value"
type = "u32"
key = false
