kind = "DojoContract"
class_hash = "0x40810848371bc14c94ae0f24530f32d84f4a0dda6ef3db25231db0b74d02665"
original_class_hash = "0x40810848371bc14c94ae0f24530f32d84f4a0dda6ef3db25231db0b74d02665"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
