kind = "DojoContract"
class_hash = "0x1473ca19990b737e9519242ef2e2d4577a2a08e00da3bc038be62b75260e66"
original_class_hash = "0x1473ca19990b737e9519242ef2e2d4577a2a08e00da3bc038be62b75260e66"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
