kind = "DojoContract"
class_hash = "0x7b3da795f6f42aa98e6a045cb1ae83a76ca8f8037ab9078da6320f0a8584842"
original_class_hash = "0x7b3da795f6f42aa98e6a045cb1ae83a76ca8f8037ab9078da6320f0a8584842"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/threed_2048_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "threed_2048::systems::actions::actions"
